# Generated by Django 3.2.9 on 2021-12-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='koniec_realizacji',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='rozpoczecie_realizacji',
            field=models.DateTimeField(null=True),
        ),
    ]
