# Generated by Django 3.2.9 on 2021-12-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_zlecenie_typ_pojazdu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przekroczenie',
            name='polozenie',
        ),
        migrations.RemoveField(
            model_name='przekroczenie',
            name='pomiar',
        ),
        migrations.RemoveField(
            model_name='przekroczenie',
            name='zdjecie',
        ),
    ]
