# Generated by Django 3.2.9 on 2021-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211229_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomiar',
            name='czy_norma_przekroczona',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Przekroczenie',
        ),
    ]
